### ISSUE TITLE
Can't use auto-service with annotation processor with IDEA with this plugin?

### ISSUE THREAD

**Issue by SoniEx2** [tbroyer/gradle-apt-plugin#52] opened 2017-07-22 01:49 UTC
I'm trying to write an annotation processor and I can't use an annotation processor to generate the annotation processor with IDEA.

Basically, this plugin + my annotation processor + the annotation processor that I'm trying to use + IDEA = impossible to compile.

Edit: IDEA bug? Seems enabling gradle-assisted compilation (aka "Delegate IDE build/run actions to gradle") fixes it.

**Comment by tbroyer** [comment] 2017-07-24 10:54
Looks like a dupe of #44 right? (tl;dr: yes, a bug in IDEA: https://github.com/tbroyer/gradle-apt-plugin/issues/44#issuecomment-300106844)

**Comment by SoniEx2** [comment] 2017-07-24 15:07
Uh, the errors imply more that it's trying to use the compilation output as an annotation processor... So if it is an IDEA bug, it's not the same IDEA bug.

**Comment by tbroyer** [comment] 2017-07-24 15:25
Then could you please give more details as to your problem? I don't understand what your setup is, what you're trying to do, what you experience nor what you'd expect.

**Comment by SoniEx2** [comment] 2017-07-24 15:56
I'm trying to use auto-service for an annotation processor. So I'm using an annotation processor to literally make an annotation processor.

I have an annotation class and an annotation processor class with `@AutoProcessor`. With the default configuration, this compiles the first time, but errors every other time, unless I delete the output directory.

IDEA bug?

**Comment by tbroyer** [comment] 2017-07-24 16:21
Which error do you have? Which IDEA version do you use? How did you import your project into IDEA? (see various options and variants in the README)

**Comment by SoniEx2** [comment] 2017-07-24 16:24
```
When using the Gradle integration in IntelliJ IDEA however, rather than the idea task, you'll have to manually enable annotation processing: in Settings… → Build, Execution, Deployment → Compiler → Annotation Processors, check Enable annotation processing and Obtain processors from project classpath.
```

(skipped the gradle behaviour part but w/e)

IDEA 2017.1.4

**Comment by tbroyer** [comment] 2017-07-25 11:56
> (skipped the gradle behaviour part but w/e)

Did you only skip it in the copy/paste above? or in your setup?

Also, you still did not answer: which error do you have?

Do you have a small repro case that I could test on my side?

**Comment by SoniEx2** [comment] 2017-07-25 13:26
Do the setup, skip the gradle behaviour part (the way it's worded implies it's optional), create a dummy annotation, create a dummy annotation processor, use `@AutoService` on the annotation processor instead of adding meta-inf and such.

**Comment by tbroyer** [comment] 2017-07-25 15:20
Definitely an IDEA bug. You can easily reproduce it with a small project from scratch in IDEA, without Gradle involved at all. I, for one, highly suggest delegating build actions to Gradle. Alternatively, in your "annotation processing" settings, list processors explicitly to tell IDEA to only run the `com.google.auto.service.processor.AutoServiceProcessor`, and not try to run your own processor.

**Closed by tbroyer** 2017-07-25 15:20 UTC
