### ISSUE TITLE
How to exclude generation every time when we do the compilation?

### ISSUE THREAD

**Issue by mayuran19** [tbroyer/gradle-apt-plugin#74] opened 2017-12-07 09:26 UTC
Hi,

I have changed the generatedSourceDestinationDir to src directory. Now I have having a problem that every time when I compile the project, it is getting executed. How can I stop this behavior?

**Comment by tbroyer** [comment] 2017-12-07 11:19
Isn't this what you'd expect from annotation processors?

If you want to do things in several steps, you'd have to run a first _compilation_ with `-proc:only` to generate sources (without actually compiling anything), then another run with `-proc:none` (or without the annotation processors) and the sources generated by the first run to actually compile everything.
Now, depending on what workflow you actually want, you could also configure `aptOptions.annotationProcessing` to true/false and add the generated sources as a source directory (or delete it in a `doFirst` on the `compileJava` task) depending on which behavior you want. In any case this is beyond the scope of this plugin.

Duplicate of #71

**Closed by tbroyer** 2017-12-07 11:19 UTC
